<?php

namespace WCS\putyourzickBundle\Repository;

/**
 * LikePlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikePlaylistRepository extends \Doctrine\ORM\EntityRepository
{
}
