wcs_putyourzick_homepage:
    path:     /
    defaults: { _controller: WCSputyourzickBundle:Default:index }

wcs_putyourzick_inscription:
    path:    /inscription
    defaults: { _controller: WCSputyourzickBundle:User:inscription}

wcs_putyourzick_login:
    path:    /login
    defaults: { _controller: WCSputyourzickBundle:User:login}

wcs_putyourzick_logout:
    path: /user/logout

wcs_sputyourzick_homepage:
    path:     /
    defaults: { _controller: WCSputyourzickBundle:Default:index }

wcs_sputyourzick_get_playlist:
    path:     /getplaylist
    defaults: { _controller: WCSputyourzickBundle:Playlist:get }

wcs_putyourzick_add_playlist:
    path:     /user/addplaylist
    defaults: { _controller: WCSputyourzickBundle:Playlist:add }

wcs_sputyourzick_edit_playlist:
    path:     /user/editplaylist/{id}
    defaults: { _controller: WCSputyourzickBundle:Playlist:edit }

wcs_sputyourzick_delete_playlist:
    path:     /user/deleteplaylist/{id}
    defaults: { _controller: WCSputyourzickBundle:Playlist:delete }


