wcs_putyourzick_homepage:
    path:     /
    defaults: { _controller: WCSputyourzickBundle:Default:index }

wcs_putyourzick_inscription:
    path:    /inscription
    defaults: { _controller: WCSputyourzickBundle:inscription}

wcs_putyourzick_login:
    path:    /login
    defaults: { _controller: WCSputyourzickBundle:login}

wcs_putyourzick_logout:
    path: /user/logout

